name: Deploy on push
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Docker registry
        run: doctl registry login

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save hub

      - name: Debug view of environment variables
        uses: hmarr/debug-action@v1.0.0

      - id: build-and-deploy
        name: Build and push docker images
        run: .devops/deploy.sh
